apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp
  labels:
    app: restaurantapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurantapp
  template:
    metadata:
      labels:
        app: restaurantapp
    spec:
      containers:
      - name: restaurantapp
        image: RESTAURANTAPP_IMAGE_TAG
        ports:
        - containerPort: 1919
          name: http

        env:
        - name: REDIS_HOST
          value: "restaurantapp-redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: PORT
          value: "1919"

        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: uri

        - name: TLS_CERT_PATH
          value: "/etc/certs/tls.crt"
        - name: TLS_KEY_PATH
          value: "/etc/certs/tls.key"
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/certs
          readOnly: true
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      volumes:
      - name: tls-certs
        secret:
          secretName: backend-tls-secret
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: restaurantapp-redis
  labels:
    app: restaurantapp-redis
spec:
  serviceName: restaurantapp-redis-service
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp-redis
  template:
    metadata:
      labels:
        app: restaurantapp-redis
    spec:
      containers:
      - name: restaurantapp-redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi