apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp-frontend
  labels:
    app: restaurantapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurantapp-frontend
  template:
    metadata:
      labels:
        app: restaurantapp-frontend
    spec:
      containers:
      - name: restaurantapp-frontend
        image: FRONTEND_IMAGE_TAG
        ports:
        - containerPort: 5173
        env:
        - name: VITE_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VITE_GOOGLE_CLIENT_ID
        - name: VITE_API_URL
          value: "restaurantapp-backend-service"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp-backend
  labels:
    app: restaurantapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurantapp-backend
  template:
    metadata:
      labels:
        app: restaurantapp-backend
    spec:
      containers:
      - name: restaurantapp-backend
        image: BACKEND_IMAGE_TAG
        ports:
        - containerPort: 1919
        env:
        - name: REDIS_HOST
          value: "restaurantapp-redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: PORT
          value: "1919"
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: uri
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: restaurantapp-redis
  labels:
    app: restaurantapp-redis
spec:
  serviceName: restaurantapp-redis-service
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp-redis
  template:
    metadata:
      labels:
        app: restaurantapp-redis
    spec:
      containers:
      - name: restaurantapp-redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi