version: '3.8'

services:
  app:
    build: .
    ports:
      - "1919:1919"  # Backend port
      - "5173:5173"  # Frontend port
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    secrets:
      - mongodb_uri
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data: 

secrets:
  mongodb_uri:
    file: .env 