apiVersion: v1
kind: Service
metadata:
  name: restaurantapp-service
spec:
  selector:
    app: restaurantapp
  ports:
    - name: http
      port: 80
      targetPort: 1919
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: restaurantapp-redis-service
spec:
  selector:
    app: restaurantapp-redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis