name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  FRONTEND_IMAGE: restaurantapp-frontend
  BACKEND_IMAGE: restaurantapp-backend

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |-
        gcloud --quiet auth configure-docker

    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Build Frontend Docker image
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$GITHUB_SHA" \
          --file frontend.Dockerfile \
          .

    - name: Build Backend Docker image
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$BACKEND_IMAGE:$GITHUB_SHA" \
          --file backend.Dockerfile \
          .

    - name: Push Frontend Docker image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$GITHUB_SHA"

    - name: Push Backend Docker image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$BACKEND_IMAGE:$GITHUB_SHA"

    - name: Deploy
      run: |-
        # Replace the image names in the k8s template
        sed -i "s|gcr.io/PROJECT_ID/restaurantapp-frontend:TAG|gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$GITHUB_SHA|g" deployment.yml
        sed -i "s|gcr.io/PROJECT_ID/restaurantapp-backend:TAG|gcr.io/$PROJECT_ID/$BACKEND_IMAGE:$GITHUB_SHA|g" deployment.yml
        
        # Apply the deployment
        kubectl apply -f deployment.yml
        
        # Verify deployment
        kubectl rollout status deployment/restaurantapp-frontend
        kubectl rollout status deployment/restaurantapp-backend
        kubectl get services -o wide