name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPO_NAME: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  FRONTEND_IMAGE: restaurantapp-frontend
  BACKEND_IMAGE: restaurantapp-backend

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.image-tag }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as a credential helper
      run: |-
        gcloud auth configure-docker us-west2-docker.pkg.dev

    - name: Build and Push Frontend Docker image
      id: meta
      run: |-
        IMAGE_TAG=us-west2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$FRONTEND_IMAGE:$GITHUB_SHA
        docker build -t $FRONTEND_IMAGE -f frontend.Dockerfile .
        docker tag $FRONTEND_IMAGE $IMAGE_TAG
        docker push $IMAGE_TAG
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.image-tag }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as a credential helper
      run: |-
        gcloud auth configure-docker us-west2-docker.pkg.dev

    - name: Build and Push Backend Docker image
      id: meta
      run: |-
        IMAGE_TAG=us-west2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BACKEND_IMAGE:$GITHUB_SHA
        docker build -t $BACKEND_IMAGE -f backend.Dockerfile .
        docker tag $BACKEND_IMAGE $IMAGE_TAG
        docker push $IMAGE_TAG
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Deploy to GKE
      run: |-
        # Replace the image names in the k8s template
        sed -i "s|gcr.io/PROJECT_ID/restaurantapp-frontend:TAG|${{ needs.build-frontend.outputs.image-tag }}|g" deployment.yml
        sed -i "s|gcr.io/PROJECT_ID/restaurantapp-backend:TAG|${{ needs.build-backend.outputs.image-tag }}|g" deployment.yml
        
        # Apply the deployment
        kubectl apply -f deployment.yml
        
        # Verify deployment
        kubectl rollout status deployment/restaurantapp-frontend
        kubectl rollout status deployment/restaurantapp-backend
        kubectl get services -o wide