name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPO_NAME: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  FRONTEND_IMAGE: restaurantapp-frontend
  BACKEND_IMAGE: restaurantapp-backend

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Updated authentication step
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Updated setup-gcloud step
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as a credential helper
      run: |-
        gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Build and Tag Frontend Docker image
      run: |-
        docker build -t $FRONTEND_IMAGE -f frontend.Dockerfile .
        docker tag $FRONTEND_IMAGE us-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$FRONTEND_IMAGE:$GITHUB_SHA

    - name: Build and Tag Backend Docker image
      run: |-
        docker build -t $BACKEND_IMAGE -f backend.Dockerfile .
        docker tag $BACKEND_IMAGE us-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BACKEND_IMAGE:$GITHUB_SHA

    - name: Push Frontend Docker image
      run: |-
        docker push us-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$FRONTEND_IMAGE:$GITHUB_SHA

    - name: Push Backend Docker image
      run: |-
        docker push us-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BACKEND_IMAGE:$GITHUB_SHA

    - name: Deploy
      run: |-
        # Replace the image names in the k8s template
        sed -i "s|gcr.io/PROJECT_ID/restaurantapp-frontend:TAG|us-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$FRONTEND_IMAGE:$GITHUB_SHA|g" deployment.yml
        sed -i "s|gcr.io/PROJECT_ID/restaurantapp-backend:TAG|us-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BACKEND_IMAGE:$GITHUB_SHA|g" deployment.yml
        
        # Apply the deployment
        kubectl apply -f deployment.yml
        
        # Verify deployment
        kubectl rollout status deployment/restaurantapp-frontend
        kubectl rollout status deployment/restaurantapp-backend
        kubectl get services -o wide